using Microsoft.CodeAnalysis;

namespace Guyl.Logger.Editor
{
	[Generator]
	public class ClassGenerator : ISourceGenerator
	{
		public void Initialize( GeneratorInitializationContext context )
		{
			throw new System.NotImplementedException();
		}

		public void Execute( GeneratorExecutionContext context )
		{
			// Find the main method
			var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

			// Try this https://github.com/AnnulusGames/UnityCodeGen
			
			// Build up the source code
			string source = $@"// <auto-generated/>
using System;

namespace {mainMethod.ContainingNamespace.ToDisplayString()}
{{
    public static partial class {mainMethod.ContainingType.Name}
    {{
        static partial void HelloFrom(string name) =>
            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
    }}
}}
";
			var typeName = mainMethod.ContainingType.Name;

			// Add the source code to the compilation
			context.AddSource($"{typeName}.g.cs", source);
		}
	}
}